# Generated by Django 3.2.7 on 2022-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreward',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
