# Generated by Django 3.2.7 on 2022-05-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_myreward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
