# Generated by Django 3.2.7 on 2022-05-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_report_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreward',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='myrewards', to='quiz.RewardMenu'),
        ),
    ]
